# Generated by Django 3.2.24 on 2024-02-29 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, null=True)),
                ('price', models.CharField(max_length=60, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('category', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
